services:
  migration:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    restart: no
    environment:
      - 'DOTENV_PRIVATE_KEY_PRODUCTION=${DOTENV_PRIVATE_KEY_PRODUCTION}'
      - 'BETTER_AUTH_URL=${BETTER_AUTH_URL}'
    networks:
      - coolify

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - 'DOTENV_PRIVATE_KEY_PRODUCTION=${DOTENV_PRIVATE_KEY_PRODUCTION}'
      - 'BETTER_AUTH_URL=${BETTER_AUTH_URL}'
      - 'NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}'
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - coolify

networks:
  coolify:
    external: true
