overrides:
  kysely: "0.28.1"
allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@swc/core': false
  lefthook: true
  msw: false
  prisma: true
  sharp: false
  unrs-resolver: false
